import { StyleSheet, Dimensions } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  map: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  loadingContainer:{
    flexGrow: 1,
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoContainer: {
    position: 'absolute',
    top: 40,
    left: 20,
    right: 20,
    zIndex: 1,
    backgroundColor: 'rgba(255,255,255,0.95)',
    padding: 15,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
    textAlign: 'center',
  },
  instruction: {
    fontSize: 16,
    color: '#0066ff',
    marginBottom: 8,
    fontWeight: '500',
  },
  speed: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  street: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  eta: {
    fontSize: 14,
    color: '#0066ff',
    marginBottom: 4,
    fontWeight: '500',
  },
  distance: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  turnSignal: {
    position: 'absolute',
    backgroundColor: 'rgba(255, 165, 0, 0.7)',
    padding: 5,
    borderRadius: 3,
    fontSize: 12,
  },
  progressContainer: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(255,255,255,0.95)',
    padding: 10,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  backButton: {
    position: 'absolute',
    top: 10,
    left: 10,
    zIndex: 2,
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  backButtonText: {
    fontSize: 16,
    color: '#0066ff',
    fontWeight: '600',
  },
  routeInfoBanner: {
    backgroundColor: '#e3f2fd',
    padding: 10,
    borderRadius: 8,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#0066ff',
  },
  routeInfoText: {
    fontSize: 13,
    color: '#1976d2',
    fontWeight: '500',
  },
});

export default styles;