import { StyleSheet, Dimensions } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  map: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  loadingContainer:{
    flexGrow: 1,
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoContainer: {
    position: 'absolute',
    top: 40,
    left: 20,
    right: 20,
    zIndex: 1,
    backgroundColor: 'rgba(255,255,255,0.95)',
    padding: 15,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
    textAlign: 'center',
  },
  instruction: {
    fontSize: 16,
    color: '#0066ff',
    marginBottom: 8,
    fontWeight: '500',
  },
  speed: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  street: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  eta: {
    fontSize: 14,
    color: '#0066ff',
    marginBottom: 4,
    fontWeight: '500',
  },
  distance: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  turnSignal: {
    position: 'absolute',
    backgroundColor: 'rgba(255, 165, 0, 0.7)',
    padding: 5,
    borderRadius: 3,
    fontSize: 12,
  },
  progressContainer: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(255,255,255,0.95)',
    padding: 10,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  backButton: {
    position: 'absolute',
    top: 10,
    left: 10,
    zIndex: 2,
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  backButtonText: {
    fontSize: 16,
    color: '#0066ff',
    fontWeight: '600',
  },
  routeInfoBanner: {
    backgroundColor: '#e3f2fd',
    padding: 10,
    borderRadius: 8,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#0066ff',
  },
  routeInfoText: {
    fontSize: 13,
    color: '#1976d2',
    fontWeight: '500',
  },
  vehicleMarker: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehiclePulse: {
    position: 'absolute',
    width: 70,
    height: 70,
    backgroundColor: '#FF5722',
    borderRadius: 35,
  },
  vehicleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  directionArrow: {
    alignItems: 'center',
    marginBottom: 2,
  },
  arrowTip: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 7,
    borderRightWidth: 7,
    borderBottomWidth: 12,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#FF5722',
    shadowColor: '#FF5722',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  vehicleDirection: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  carBody: {
    width: 34,
    height: 48,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  carFront: {
    width: 20,
    height: 12,
    backgroundColor: '#FF5722',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    marginBottom: 1,
    shadowColor: '#FF5722',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.6,
    shadowRadius: 2,
    elevation: 3,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 2,
  },
  headlightsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 16,
  },
  headlight: {
    width: 3,
    height: 3,
    backgroundColor: '#FFEB3B',
    borderRadius: 1.5,
    shadowColor: '#FFEB3B',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 3,
  },
  carMain: {
    width: 26,
    height: 16,
    backgroundColor: '#FF9800',
    borderRadius: 3,
    marginBottom: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#F57C00',
  },
  carWindow: {
    width: 18,
    height: 8,
    backgroundColor: '#64B5F6',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: '#42A5F5',
  },
  carBack: {
    width: 28,
    height: 18,
    backgroundColor: '#E65100',
    borderRadius: 3,
    borderWidth: 2,
    borderColor: '#BF360C',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cargoPattern: {
    width: 22,
    height: 14,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  cargoLine: {
    width: 18,
    height: 2,
    backgroundColor: '#FF6E40',
    borderRadius: 1,
  },
  vehicleIcon: {
    fontSize: 24,
    textAlign: 'center',
  },
  startMarker: {
    alignItems: 'center',
  },
  endMarker: {
    alignItems: 'center',
  },
  markerPin: {
    width: 36,
    height: 36,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
    borderWidth: 2,
    borderColor: '#4285F4',
  },
  markerText: {
    fontSize: 20,
  },
  markerStem: {
    width: 2,
    height: 12,
    backgroundColor: '#4285F4',
  },
});

export default styles;