import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  vehicleMarker: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehiclePulse: {
    position: 'absolute',
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#FF9800',
  },
  vehicleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  directionArrow: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderBottomWidth: 10,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#D32F2F',
    marginBottom: 2,
  },
  arrowTip: {
    width: 0,
    height: 0,
  },
  vehicleDirection: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  carBody: {
    width: 34,
    height: 48,
    alignItems: 'center',
    justifyContent: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  carFront: {
    width: 20,
    height: 12,
    backgroundColor: '#FF5722',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E65100',
  },
  headlightsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
    marginTop: 2,
  },
  headlight: {
    width: 3,
    height: 3,
    backgroundColor: '#FFF',
    borderRadius: 1.5,
  },
  carMain: {
    width: 26,
    height: 16,
    backgroundColor: '#FF9800',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#F57C00',
  },
  carWindow: {
    width: 16,
    height: 8,
    backgroundColor: '#81D4FA',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: '#039BE5',
  },
  carBack: {
    width: 28,
    height: 18,
    backgroundColor: '#E65100',
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#BF360C',
  },
  cargoPattern: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '70%',
  },
  cargoLine: {
    width: 2,
    height: 12,
    backgroundColor: '#D84315',
    borderRadius: 1,
  },
});
